CREATE TABLE `suggestion_task` (
  `id` BIGINT NOT NULL,
  `submission_id` BIGINT NOT NULL,
  `team_id` BIGINT NOT NULL,
  `problem_id` BIGINT NOT NULL,
  `review_task_id` BIGINT NOT NULL,
  `workflow_version` VARCHAR(40) NOT NULL,
  `review_workflow_version` VARCHAR(40) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `prompt_snapshot` LONGTEXT NOT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_run_at` DATETIME NOT NULL,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `error_message` VARCHAR(500) NULL,
  `result_json` JSON NULL,
  `model_name` VARCHAR(100) NULL,
  `ai_call_id` VARCHAR(64) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_submission_workflow` (`submission_id`, `workflow_version`),
  INDEX `idx_team_create_time` (`team_id`, `create_time`),
  INDEX `idx_status_next_run_at` (`status`, `next_run_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='论文结构化改善建议任务';
