server:
  port: 8080

spring:

  application:
    name: OssDemo
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com  # 地域节点
    access-key-id: ${OSS_ACCESS_KEY_ID}           # 密钥ID
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}   # 密钥秘钥
    bucket-name: leet-model              # 存储空间名
    region: cn-beijing  # 访问地域
