CREATE TABLE `ranking_snapshot` (
  `id` BIGINT NOT NULL,
  `batch_id` VARCHAR(36) NOT NULL,
  `problem_id` BIGINT NOT NULL,
  `team_id` BIGINT NOT NULL,
  `team_name` VARCHAR(100) NOT NULL,
  `submission_id` BIGINT NOT NULL,
  `review_task_id` BIGINT NOT NULL,
  `workflow_version` VARCHAR(40) NOT NULL,
  `score` DECIMAL(5,2) NOT NULL,
  `rank_no` INT NOT NULL,
  `submitted_at` DATETIME NOT NULL,
  `review_finished_at` DATETIME NOT NULL,
  `computed_at` DATETIME NOT NULL,
  `current_marker` TINYINT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_batch_team` (`batch_id`, `team_id`),
  UNIQUE INDEX `uk_problem_team_current` (`problem_id`, `team_id`, `current_marker`),
  INDEX `idx_problem_current_rank` (`problem_id`, `current_marker`, `rank_no`),
  INDEX `idx_team_current` (`team_id`, `current_marker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='论文排行可追溯快照';
