CREATE TABLE `message_inbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consumer_group` VARCHAR(255) NOT NULL,
  `event_id` VARCHAR(36) NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `source_service` VARCHAR(100) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `consumed_at` DATETIME(3) NULL,
  `create_time` DATETIME(3) NOT NULL,
  `update_time` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_message_inbox_consumer_event` (`consumer_group`, `event_id`),
  INDEX `idx_message_inbox_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排行服务消费 Inbox';

CREATE TABLE `message_outbox` (
  `event_id` VARCHAR(36) NOT NULL,
  `topic` VARCHAR(255) NOT NULL,
  `tag` VARCHAR(80) NOT NULL,
  `message_key` VARCHAR(255) NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `schema_version` INT NOT NULL,
  `source_service` VARCHAR(100) NOT NULL,
  `aggregate_type` VARCHAR(100) NOT NULL,
  `aggregate_id` VARCHAR(100) NOT NULL,
  `idempotency_key` VARCHAR(255) NOT NULL,
  `trace_id` VARCHAR(100) NOT NULL,
  `payload_json` LONGTEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME(3) NOT NULL,
  `lease_owner` VARCHAR(160) NULL,
  `lease_expires_at` DATETIME(3) NULL,
  `broker_message_id` VARCHAR(255) NULL,
  `last_error` VARCHAR(500) NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `published_at` DATETIME(3) NULL,
  `create_time` DATETIME(3) NOT NULL,
  `update_time` DATETIME(3) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `uk_outbox_event_idempotency` (`event_type`, `idempotency_key`),
  INDEX `idx_message_outbox_dispatch` (`status`, `next_attempt_at`, `lease_expires_at`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='排行服务可靠消息 Outbox';

CREATE TABLE `ranking_rebuild_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `problem_id` BIGINT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `requested_revision` BIGINT NOT NULL DEFAULT 0,
  `running_revision` BIGINT NULL,
  `completed_revision` BIGINT NOT NULL DEFAULT 0,
  `source_fingerprint` VARCHAR(64) NULL,
  `trace_id` VARCHAR(100) NOT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_run_at` DATETIME(3) NOT NULL,
  `lease_owner` VARCHAR(160) NULL,
  `lease_token` VARCHAR(36) NULL,
  `lease_expires_at` DATETIME(3) NULL,
  `heartbeat_at` DATETIME(3) NULL,
  `recovery_count` INT NOT NULL DEFAULT 0,
  `last_error` VARCHAR(500) NULL,
  `create_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `update_time` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_ranking_rebuild_problem` (`problem_id`),
  INDEX `idx_ranking_rebuild_claim` (`status`, `next_run_at`, `lease_expires_at`, `update_time`),
  INDEX `idx_ranking_rebuild_lease` (`lease_owner`, `lease_token`, `lease_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='按题目合并的排行重建任务';
