server:
  port: 8090

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /internal/ai/v3/api-docs
