server:
  port: 8080


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# PageHelper 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

spring:
  application:
    name: LeetModel
  datasource:
    url: jdbc:mysql://47.111.180.134:3306/leet-model
    username: root
    password: Senior666^
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    port: 587
    username: 2042175308@qq.com
    password: wnpwqjwhaziicgfh  # QQ 邮箱需使用授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  security:
#    user:
#      name: root
#      password: 44448888


#jwt:
#  secret-key: your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
#  token-expiration: 86400000 # 24小时 (毫秒)
