server:
  port: 8080


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# PageHelper 分页配置
page-helper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true


spring:
  application:
    name: LeetModel
  datasource:
    url: ${LM_MYSQL_URL} # mysql的数据库地址
    username: ${LM_MYSQL_USER} # 数据库用户名
    password: ${LM_MYSQL_PASSWORD} # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    port: 587
    username: ${LM_QQ_MAIL_USER} # QQ 邮箱
    password: ${LM_QQ_MAIL_AUTH_CODE} # QQ 邮箱需使用授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${LM_REDIS_HOST} # redis 服务器 IP
      port: ${LM_REDIS_PORT:6379}
      password: ${LM_REDIS_PASSWORD} # 环境变量中配置 redis 密码
  ai:
    openai:
      api-key: ${LM_DEEPSEEK_API_KEY} # Deepseek 的 API KEY
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com



aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com         # 地域节点
    access-key-id: ${LM_OSS_ACCESS_KEY_ID}           # 密钥 ID
    access-key-secret: ${LM_OSS_ACCESS_KEY_SECRET}   # 密钥秘钥
    bucket-name: leet-model                       # 存储空间名
    region: cn-beijing                            # 访问地域


leet-model:
  auth:
    email-code:
      redis-code-key-prefix: "auth:email:code:"
      redis-cooldown-key-prefix: "auth:email:cooldown:"
      redis-code-expire: 5m
      redis-send-cooldown: 60s

jwt:
  secret-key: your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
  token-expiration: 259200000 # 3 * 24 小时 (毫秒)
