server:
  port: 8080


mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

# PageHelper 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

spring:
  application:
    name: LeetModel
  datasource:
    url: ${MYSQL_URL} # mysql的数据库地址
    username: ${MYSQL_USER} # 数据库用户名
    password: ${MYSQL_PASSWORD} # 数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  mail:
    host: smtp.qq.com
    port: 587
    username: ${QQ_MAIL_USER} # QQ 邮箱
    password: ${QQ_MAIL_AUTH_CODE} # QQ 邮箱需使用授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: ${REDIS_HOST} # redis 服务器 IP
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD} # 环境变量中配置 redis 密码
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY} # Deepseek 的 API KEY
      chat:
        options:
          model: deepseek-chat
      base-url: https://api.deepseek.com





#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  security:
#    user:
#      name: root
#      password: 44448888


#jwt:
#  secret-key: your-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
#  token-expiration: 86400000 # 24小时 (毫秒)

ai:
  is-prompt-load-from-file: true

# 火山引擎相关配置
ark:
  ai:
    base-url: https://ark.cn-beijing.volces.com/api/v3
    model: deepseek-v3-2-251201
    api-key: ${ARK_API_KEY:} # 火山引擎 API KEY