CREATE TABLE `ai_call_log` (
  `id` BIGINT NOT NULL,
  `call_id` VARCHAR(64) NOT NULL,
  `scene` VARCHAR(30) NOT NULL,
  `provider` VARCHAR(30) NOT NULL,
  `model` VARCHAR(100) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `prompt_tokens` BIGINT NULL,
  `completion_tokens` BIGINT NULL,
  `reasoning_tokens` BIGINT NULL,
  `total_tokens` BIGINT NULL,
  `usage_complete` TINYINT NOT NULL DEFAULT 0,
  `duration_ms` BIGINT NOT NULL,
  `error_code` INT NULL,
  `error_message` VARCHAR(300) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_call_id` (`call_id`),
  INDEX `idx_status_create_time` (`status`, `create_time`),
  INDEX `idx_scene_create_time` (`scene`, `create_time`),
  INDEX `idx_provider_model_time` (`provider`, `model`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='不含业务正文的AI调用审计摘要';
