CREATE TABLE `ai_call_task` (
  `id` BIGINT NOT NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `call_id` VARCHAR(64) NOT NULL,
  `caller_service` VARCHAR(64) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `call_type` VARCHAR(20) NOT NULL,
  `feature_code` VARCHAR(64) NOT NULL,
  `operation_code` VARCHAR(64) NOT NULL,
  `declared_priority` VARCHAR(10) NOT NULL,
  `effective_priority` VARCHAR(10) NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `model_execution_config_version` VARCHAR(100) NULL,
  `request_hash` CHAR(64) NOT NULL,
  `request_payload` MEDIUMTEXT NOT NULL,
  `result_payload` MEDIUMTEXT NULL,
  `deadline` DATETIME(3) NOT NULL,
  `max_queue_wait_ms` BIGINT NOT NULL,
  `lease_owner` VARCHAR(100) NULL,
  `lease_expiry` DATETIME(3) NULL,
  `attempt_count` INT NOT NULL DEFAULT 0,
  `version` BIGINT NOT NULL DEFAULT 0,
  `cancel_requested` TINYINT NOT NULL DEFAULT 0,
  `error_code` VARCHAR(64) NULL,
  `dead_letter_reason` VARCHAR(100) NULL,
  `queued_at` DATETIME(3) NOT NULL,
  `leased_at` DATETIME(3) NULL,
  `started_at` DATETIME(3) NULL,
  `finished_at` DATETIME(3) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_task_id` (`task_id`),
  UNIQUE INDEX `uk_task_call_id` (`call_id`),
  UNIQUE INDEX `uk_task_caller_idempotency` (`caller_service`, `idempotency_key`),
  INDEX `idx_state_priority_queued_at` (`state`, `effective_priority`, `queued_at`),
  INDEX `idx_state_lease_expiry` (`state`, `lease_expiry`),
  INDEX `idx_state_deadline` (`state`, `deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI网关逻辑调用调度任务';

CREATE TABLE `ai_call_attempt` (
  `id` BIGINT NOT NULL,
  `attempt_id` VARCHAR(64) NOT NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `attempt_no` INT NOT NULL,
  `state` VARCHAR(20) NOT NULL,
  `owner` VARCHAR(100) NOT NULL,
  `new_api_request_id` VARCHAR(128) NULL,
  `http_status` INT NULL,
  `error_code` VARCHAR(64) NULL,
  `retry_after_ms` BIGINT NULL,
  `prepared_at` DATETIME(3) NOT NULL,
  `sent_at` DATETIME(3) NULL,
  `acknowledged_at` DATETIME(3) NULL,
  `finished_at` DATETIME(3) NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_attempt_id` (`attempt_id`),
  UNIQUE INDEX `uk_attempt_task_no` (`task_id`, `attempt_no`),
  INDEX `idx_task_id_state` (`task_id`, `state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI网关到new-api派发尝试';
