CREATE TABLE `message_inbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `consumer_group` VARCHAR(255) NOT NULL,
  `event_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `source_service` VARCHAR(100) NOT NULL,
  `trace_id` VARCHAR(100) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `consumed_at` DATETIME(3) NULL,
  `create_time` DATETIME(3) NOT NULL,
  `update_time` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_message_inbox_consumer_event` (`consumer_group`, `event_id`),
  INDEX `idx_message_inbox_trace` (`trace_id`, `create_time`),
  INDEX `idx_message_inbox_status_time` (`status`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `message_outbox` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `topic` VARCHAR(255) NOT NULL,
  `tag` VARCHAR(100) NOT NULL,
  `message_key` VARCHAR(100) NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `schema_version` INT NOT NULL,
  `source_service` VARCHAR(100) NOT NULL,
  `aggregate_type` VARCHAR(100) NOT NULL,
  `aggregate_id` VARCHAR(100) NOT NULL,
  `idempotency_key` VARCHAR(100) NOT NULL,
  `trace_id` VARCHAR(100) NOT NULL,
  `payload_json` JSON NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME(3) NOT NULL,
  `lease_owner` VARCHAR(100) NULL,
  `lease_expires_at` DATETIME(3) NULL,
  `broker_message_id` VARCHAR(100) NULL,
  `published_at` DATETIME(3) NULL,
  `last_error` VARCHAR(500) NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `create_time` DATETIME(3) NOT NULL,
  `update_time` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_message_outbox_event` (`event_id`),
  UNIQUE INDEX `uk_message_outbox_idempotency` (`idempotency_key`),
  INDEX `idx_message_outbox_claim` (`status`, `next_attempt_at`, `create_time`),
  INDEX `idx_message_outbox_trace` (`trace_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
