CREATE TABLE `assistant_tool_call` (
  `id` BIGINT NOT NULL,
  `conversation_id` BIGINT NOT NULL,
  `user_message_id` BIGINT NOT NULL,
  `assistant_message_id` BIGINT NOT NULL,
  `attempt_no` INT NOT NULL,
  `sequence_no` INT NOT NULL,
  `provider_tool_call_id` VARCHAR(128) NOT NULL,
  `toolset_version` VARCHAR(64) NOT NULL,
  `tool_name` VARCHAR(64) NOT NULL,
  `tool_version` VARCHAR(64) NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `arguments_json` JSON NULL,
  `result_snapshot_json` JSON NULL,
  `planning_ai_call_id` VARCHAR(64) NULL,
  `nested_ai_call_id` VARCHAR(64) NULL,
  `error_code` VARCHAR(64) NULL,
  `duration_ms` BIGINT NULL,
  `started_at` DATETIME NULL,
  `finished_at` DATETIME NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uk_message_attempt_sequence` (`assistant_message_id`, `attempt_no`, `sequence_no`),
  INDEX `idx_tool_status_create_time` (`tool_name`, `status`, `create_time`),
  INDEX `idx_conversation_create_time` (`conversation_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI客服工具调用执行事实';
