CREATE TABLE `message_outbox` (
  `event_id` VARCHAR(36) NOT NULL,
  `topic` VARCHAR(255) NOT NULL,
  `tag` VARCHAR(80) NOT NULL,
  `message_key` VARCHAR(255) NOT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `schema_version` INT NOT NULL,
  `source_service` VARCHAR(100) NOT NULL,
  `aggregate_type` VARCHAR(100) NOT NULL,
  `aggregate_id` VARCHAR(100) NOT NULL,
  `idempotency_key` VARCHAR(255) NOT NULL,
  `trace_id` VARCHAR(100) NOT NULL,
  `payload_json` LONGTEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME(3) NOT NULL,
  `lease_owner` VARCHAR(160) NULL,
  `lease_expires_at` DATETIME(3) NULL,
  `broker_message_id` VARCHAR(255) NULL,
  `last_error` VARCHAR(500) NULL,
  `occurred_at` DATETIME(3) NOT NULL,
  `published_at` DATETIME(3) NULL,
  `create_time` DATETIME(3) NOT NULL,
  `update_time` DATETIME(3) NOT NULL,
  PRIMARY KEY (`event_id`),
  UNIQUE INDEX `uk_outbox_event_idempotency` (`event_type`, `idempotency_key`),
  INDEX `idx_message_outbox_dispatch` (`status`, `next_attempt_at`, `lease_expires_at`, `create_time`),
  INDEX `idx_message_outbox_aggregate` (`aggregate_type`, `aggregate_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='提交服务可靠消息 Outbox';
