CREATE TABLE file_asset (
    id                  BIGINT       NOT NULL COMMENT '文件资产ID',
    bucket_name         VARCHAR(63)  NOT NULL COMMENT '对象存储桶',
    object_key          VARCHAR(512) NOT NULL COMMENT '桶内唯一对象Key',
    original_name       VARCHAR(255) NOT NULL COMMENT '上传时原始文件名',
    content_type        VARCHAR(127) NULL COMMENT 'MIME类型',
    file_size           BIGINT       NOT NULL DEFAULT 0 COMMENT '文件大小（字节）',
    namespace_code      VARCHAR(32)  NOT NULL COMMENT '资产命名空间',
    group_path          VARCHAR(128) NOT NULL DEFAULT '' COMMENT '逻辑分组路径',
    source_type         VARCHAR(16)  NOT NULL COMMENT 'MANUAL或DISCOVERED',
    lifecycle_status    VARCHAR(24)  NOT NULL COMMENT 'ACTIVE、DISCOVERED、PENDING_DELETE、DELETE_FAILED',
    creator_id          BIGINT       NULL COMMENT '上传管理员ID',
    delete_requested_at DATETIME(3)  NULL COMMENT '逻辑删除申请时间',
    cleanup_after       DATETIME(3)  NULL COMMENT '允许物理清理时间',
    retry_count         INT          NOT NULL DEFAULT 0 COMMENT '物理删除重试次数',
    last_error          VARCHAR(500) NULL COMMENT '最近一次清理失败原因',
    create_time         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    update_time         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    deleted             TINYINT      NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_file_asset_bucket_object (bucket_name, object_key),
    KEY idx_file_asset_query (deleted, namespace_code, group_path, lifecycle_status, create_time),
    KEY idx_file_asset_cleanup (deleted, lifecycle_status, cleanup_after)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件资产控制面元数据';
