-- V1 将 source_type 限定为只容纳 MANUAL、DISCOVERED 两个取值；
-- 业务文件登记引入 PROBLEM_ATTACHMENT、USER_AVATAR、SUBMISSION_PAPER，需要加宽该列。
ALTER TABLE `file_asset`
  MODIFY COLUMN `source_type` VARCHAR(32) NOT NULL COMMENT '文件来源类型，如MANUAL、DISCOVERED、PROBLEM_ATTACHMENT';
