route:
  receiver: local-null-default
  group_by:
    - alertname
    - service
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - receiver: local-drill-webhook
      matchers:
        - drill="true"
      group_wait: 1s
      group_interval: 1s
      repeat_interval: 1m
    - receiver: local-null-critical
      matchers:
        - severity="critical"
    - receiver: local-null-warning
      matchers:
        - severity="warning"

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal:
      - alertname
      - service

receivers:
  - name: local-null-default
  - name: local-null-warning
  - name: local-null-critical
  - name: local-drill-webhook
    webhook_configs:
      - url: http://127.0.0.1:19094/alerts
        send_resolved: true
